# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: 'latest'
    - run: uv sync
    - name: Test with pytest
      run: uv run pytest
    - name: Test CLI
      run: |
        # Basic test
        uv run csv-metadata-quality -i data/test.csv -o /tmp/test.csv
        # Test with unsafe fixes
        uv run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -u
        # Test with experimental checks
        uv run csv-metadata-quality -i data/test.csv -o /tmp/test.csv -e
        # Test with AGROVOC validation
        uv run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject
        # Test with AGROVOC validation (and dropping invalid)
        uv run csv-metadata-quality -i data/test.csv -o /tmp/test.csv --agrovoc-fields dcterms.subject -d
